### ISSUE TITLE
biomart error: 502 internal error - server connection terminated

### ISSUE THREAD

**Issue by gpcr** [pbnjay/lollipops#10]
@pbnjay : thanks for creating wondeful tool to represent variants

I am getting "biomart error: 502 internal error - server connection terminated"
checked it on multiple computers...

Is there a way to select the biomart mirror?

**Comment by pbnjay** [comment]
Easiest thing is to just skip biomart altogether by providing the uniprot ID with -U

But if you want to mess with the code, you could change this line: https://github.com/pbnjay/lollipops/blob/master/data/fetch_data.go#L21
And then rebuild with 'go build .'
