### ISSUE TITLE
biomart error: 301 Moved Permanently

### ISSUE THREAD

**Issue by chunwanlai** [pbnjay/lollipops#11]
Dear author,

I have tried to run this command today, but it was not successful.

./lollipops \
-labels \
-hide-disordered \
-w=900 \
SMAD4

This is the error message that I have received:
biomart error: 301 Moved Permanently

Is possible that the URL or web link has been changed? Thanks a lot for providing this great tool for the bioinformatics community!

**Comment by pbnjay** [comment]
Biomart has been changing and breaking things a lot lately... I'd recommend providing the Uniprot ID with -U instead of the gene symbol.

**Comment by chunwanlai** [comment]
Using the -U option works fine now. One way to work around the Biomart could be matching the gene symbol with custom scripts within the program. Hope that you may consider adding this feature. Thanks a lot for your advice!
