### ISSUE TITLE
Add option to hide domain labels

### ISSUE THREAD

**Issue by pbnjay** [pbnjay/lollipops#14]
Brought up in #13 by @tinypirate08

I think I'd look to make it a 3-value option: `fit`, `truncate`, or `off`
 - `truncate` - the current default, try to fit labels by truncating
 - `off` - hides all domain labels
 - `fit` - only show labels that fit into available space

Open to discussion

**Comment by tinypirate08** [comment]
I think all 3 options will be handy, to create publication ready images.
Sz
Szabolcs Szelinger
Research Associate
Neurogenomics Division
The Translational Genomics Research Institute (TGen)
445 N. 5th Street Phoenix AZ 85044
ph: 602-343-8723
fax:602-343-8844
sszelinger@tgen.org<mailto:sszelinger@tgen.org>


________________________________
________________________________

This electronic message is intended to be for the use only of the named recipient, and may contain information that is confidential or privileged, including patient health information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the contents of this message is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and delete and destroy all copies of this message. Thank you.

On Feb 2, 2016, at 7:24 AM, Jeremy Jay <notifications@github.com<mailto:notifications@github.com>> wrote:


Brought up in #13<https://github.com/pbnjay/lollipops/issues/13> by @tinypirate08<https://github.com/tinypirate08>

I think I'd look to make it a 3-value option: fit, truncate, or off

  *   truncate - the current default, try to fit labels by truncating
  *   off - hides all domain labels
  *   fit - only show labels that fit into available space

Open to discussion

**Comment by pbnjay** [comment]
Fixed in latest release!
