### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ojadi** [pbnjay/lollipops#16]
Creating a plot using any options (or none) other than "-labels" produces the following runtime error after attempting to draw the diagram:
<code>panic: assignment to entry in nil map</code>

**Comment by pbnjay** [comment]
`./lollipops TP53` works perfectly fine for me. Please include the full details (command line and full output) for what you're trying to do.

**Comment by pbnjay** [comment]
found it, fixed in latest release. thanks for the report
