### ISSUE TITLE
Trying to pull straight from Uniprot - pfam retrieval error

### ISSUE THREAD

**Issue by wadhamite** [pbnjay/lollipops#18]
Hiya, I'm trying to pull viral protein structures from Uniprot (has worked successfully before). 

It works for lollipops -labels -o=CMVtest.svg -U Q6SW77

But not for lollipops -labels -o=AdVtest.svg -U Q2KS23 when I get 'pfam returned an invalid result'.

Any idea why this might be? Thanks!

**Comment by pbnjay** [comment]
Looks like a bug with Pfam crashing the data used by the graphic 😢 
    http://pfam.xfam.org/protein/Q2KS23/graphic

It should look more like the data from your first example:
    http://pfam.xfam.org/protein/Q6SW77/graphic

I've emailed Pfam to see if they can correct the issue.

**Comment by wadhamite** [comment]
Cheers Jeremy, that's really appreciated - got a conference deadline coming up and would love to show them a lollipop plot...

**Comment by pbnjay** [comment]
So I just pushed [an update v1.3.2](https://github.com/pbnjay/lollipops/releases) that lets you load a local data file instead of requesting from Pfam. With your issue here, it looks like the pfam web page actually includes the data you need if you view source:  http://pfam.xfam.org/protein/Q2KS23

```
   {
      "length" : "1198",
      "regions" : [
         {
            "modelStart" : "1",
            "modelEnd" : "468",
            "colour" : "#2dcf00",
            "endStyle" : "curved",
            "display" : true,
            "end" : "927",
            "startStyle" : "curved",
            "aliEnd" : "926",
            "modelLength" : "469",
            "text" : "DNA_pol_B_2",
            "href" : "/family/PF03175",
            "metadata" : {
               "scoreName" : "e-value",
               "score" : "1.4e-168",
               "description" : "DNA polymerase type B, organellar and viral",
               "accession" : "PF03175",
               "end" : "927",
               "database" : "pfam",
               "aliEnd" : "926",
               "identifier" : "DNA_pol_B_2",
               "type" : "Family",
               "aliStart" : "443",
               "start" : "443"
            },
            "type" : "pfama",
            "aliStart" : "443",
            "start" : "443"
         }
      ],
      "markups" : [],
      "metadata" : {
         "database" : "uniprot",
         "identifier" : "Q2KS23_ADE05",
         "description" : "DNA polymerase {ECO:0000256|RuleBase:RU000442}",
         "organism" : "Human adenovirus C serotype 5 (HAdV-5) (Human adenovirus 5)",
         "accession" : "Q2KS23",
         "taxid" : "28285"
      },
      "motifs" : []
   }
```

Copy all that into `Q2KS23.json` and then run `./lollipops -labels -o=AdVtest.svg -U Q2KS23 -l Q2KS23.json` and that should let you work around the issue until Pfam can solve it.

**Comment by wadhamite** [comment]
Just like magic! I really appreciate you taking the time to work round it for me.

**Comment by pbnjay** [comment]
No prob! Got 2 birds with one stone on this update so no big deal 👍
