### ISSUE TITLE
font size change of the labels

### ISSUE THREAD

**Issue by DecodeGenome** [pbnjay/lollipops#19]
Hi,

I am wondering how to change the font size of AA labels and change the angle from 45 to 90. Thanks.

**Comment by pbnjay** [comment]
SVG Rotation is done here: https://github.com/pbnjay/lollipops/blob/master/drawing/svg.go#L88
Label font size is a few lines lower. You'll have to recompile to pull those in once you change them of course.

**Comment by DecodeGenome** [comment]
Hello Jeremy:

Thanks for your reply.

I am not computer expert. I need your more instructions.

I downloads lollipops-v1.3.2-mac64, I only can run ./lollipops xxx command, there is on where to change the code. I also tried to download source code , but I don’t know how to install it.

Would you mind guid me step-wise to change the code and install (recompile) it?

Thanks

Wei

**Comment by pbnjay** [comment]
Hi Wei,

If you're unable to understand how to change the code, I'd recommend just using it as-is and editing the resulting SVG in Adobe Illustrator or a similar tool. I don't think modifying the software is a good use of time for this request.

Cheers!

**Comment by DecodeGenome** [comment]
What you recommend is to generate the SVG without label, then add the label in illustrator? The problem is I have twenty to hundreds of mutations for dozens genes, Any other high-throughput way to do it.

Thanks anyways,

Best,

Wei
