### ISSUE TITLE
Error: Does not appear to be an R package (no DESCRIPTION)

### ISSUE THREAD

**Issue by belel** [pbnjay/lollipops#20]
Hi,
I'm trying to install the package on R, but I get:
> library(devtools)
> install_github("pbnjay/lollipops")
Downloading GitHub repo pbnjay/lollipops@master
from URL https://api.github.com/repos/pbnjay/lollipops/zipball/master
**Error: Does not appear to be an R package (no DESCRIPTION)**

Thanks a lot!

**Comment by pbnjay** [comment]
The error message is correct, this is not an R package.
