### ISSUE TITLE
CDS Mutation addition

### ISSUE THREAD

**Issue by sheucke** [pbnjay/lollipops#21]
Dear pbnjay,

do you plan to add CDS Mutation for Example TP53 **c.817C>T** (p.R273C) to visualize.

best wishes
Sebastian

**Comment by pbnjay** [comment]
The amino acid location will work using "R273C" but no, base pair positions require a lot more data and complexity about introns than we can easily get.

Related to #4 - again happy to accept a pull request but this is a large effort.
