### ISSUE TITLE
Change shape parameter

### ISSUE THREAD

**Issue by Steven-N-Hart** [pbnjay/lollipops#22]
Where would I change the code to have the user input an optional shape parameter (For a given variant to not be a circle)? I'm not a GO programmer, but could try if I got pointed in the right direction.

**Comment by pbnjay** [comment]
For SVG output, you could change the SVG shape used on this line:
https://github.com/pbnjay/lollipops/blob/master/drawing/svg.go#L84

For PNG output, you'll have to write some code to generate the shape and refer to it here:
https://github.com/pbnjay/lollipops/blob/master/drawing/png.go#L96

Squares and Triangles should be pretty straightforward at least. What do you have in mind for specifying shape parameters?

**Comment by pbnjay** [comment]
I'm assuming you took a different direction, but if you did implement this, feel free to submit a PR.
