### ISSUE TITLE
Is there a way to specify mutations some as upword lines (current) and others a downward line?

### ISSUE THREAD

**Issue by gpcr** [pbnjay/lollipops#23]
![image](https://cloud.githubusercontent.com/assets/2575021/20847677/258a5c06-b89d-11e6-8d4f-35c70bc3fff5.png)

thanks

**Comment by pbnjay** [comment]
Long story short: No.

Feel free to make the change yourself, but it would require removing the axis and tick generation code (or altering it substantially) in addition to altering the lollipop drawing code to work in both directions, AND a way to mark mutations that should appear on the opposite side of the plot. A lot of work, especially for a feature probably not relevant to individual samples.

Unless you really are doing a lot of these and need to automate it, it would be substantially faster to just generate 2 images and edit them by hand in Illustrator.
