### ISSUE TITLE
Wrong Output for gene CHL1

### ISSUE THREAD

**Issue by ojadi** [pbnjay/lollipops#24]
The lolliplot output for gene CHL1 produces a plot for the gene DDX11.

**Comment by pbnjay** [comment]
DDX11 has a known alias of CHL1, this is one of the many issues with using gene symbols as input. In lieu of writing 100s of lines of code to make sure to pick the right version of an ambiguous symbol, I suggest using the -U option to provide a specific Uniprot ID.
