### ISSUE TITLE
Generate lollipops graph for genes instead of proteins

### ISSUE THREAD

**Issue by kalon33** [pbnjay/lollipops#25]
First, thanks for your work that is pretty useful.

As I'm working on genes with mutations leading to splicing defects notably, and dealing with c. and p. nomenclatures (HGVS), I would be interested in being able to do these kind of graphs on genes (keeping annotations of gene parts mapping to protein domains), using HGVS nomenclatures if possible. Do you thing it would be possible to implement this, or do you know a tool that performs this?

I have a long list of mutations to represent on the graph, and the intron/exon view is needed to properly visualize splicing mutations.

Thanks for your help.

**Comment by pbnjay** [comment]
FWIW, You should be able to use any "p." nomenclature by just stripping the prefix.

This is a pretty common request (see #4 and #21), but entails a pretty significant rewrite and Pfam (used for the protein domain structure) does not have any splice site data to aid the task.

If you know of a resource for cdna->aa mapping and splice site locations that is easily accessible and can be linked to the Pfam accession directly then I could explore further. I'm happy to accept any pull requests to implement this feature also.

**Comment by kalon33** [comment]
Does it allow currently 3 symbols AA name or only one (Ala for A, Cys for C...)? 

I know of such tools but not freely available (Alamut notably). Splice site data is apparently available on ENSEMBL. Spliced cDNA could be converted to AA using one of the ExPASy tools. But I don't know how to link to Pfam then... 

Thanks for your answer 

----- Mail original -----

De: "Jeremy Jay" <notifications@github.com> 
À: "pbnjay/lollipops" <lollipops@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 7 Septembre 2017 16:34:38 
Objet: Re: [pbnjay/lollipops] Generate lollipops graph for genes instead of proteins (#25) 



FWIW, You should be able to use any "p." nomenclature by just stripping the prefix. 

This is a pretty common request (see #4 and #21 ), but entails a pretty significant rewrite and Pfam (used for the protein domain structure) does not have any splice site data to aid the task. 

If you know of a resource for cdna->aa mapping and splice site locations that is easily accessible and can be linked to the Pfam accession directly then I could explore further. I'm happy to accept any pull requests to implement this feature also.

**Comment by kalon33** [comment]
The kind of p. nomenclature I have is p.Val220IlefsX4 for example.

**Comment by pbnjay** [comment]
> Does it allow currently 3 symbols AA name or only one (Ala for A, Cys for C...)?
Yes, it doesn't parse these, it only checks if they are equal for (non-)synonymous color coding. In your example "Val" != "IlefsX4" so it should color the frameshift as non-synonymous.

**Comment by kalon33** [comment]
There's also a lot of data on uniprot for example: http://www.uniprot.org/uniprot/P38398 (BRCA1_HUMAN)

**Comment by kalon33** [comment]
@pbnjay If you go to http://www.uniprot.org/uniprot/P38398 (BRCA1_HUMAN reference), and then took the first ccds sequence from there, which correspond to the canonical isoform P38398-1 (CCDS11453.1), you are sent to https://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&GO=MainBrowse&DATA=CCDS11453.1 and are able to retrieve there linked nucleotide sequence that is the basis of c. annotation with latest assembly. 

For splicing data, you could retrieve NM RefSeq data linked to that isoform in the uniprot data, that refers to https://www.ncbi.nlm.nih.gov/nuccore/NM_007294.3 . There you have the whole gene sequence annotated (with intron/exon positions) and also translation (that is the same as the one from the previous link).

Do you think that would be usable and doable to implement this?

**Comment by pbnjay** [comment]
Like I said previously, what you are asking would require a significant effort (at least doubling the amount of work already put into this). I'm happy to make small modifications, but unless you are willing to fund this effort I cannot build it this for you since my time is committed to other projects.

I'm happy to accept pull requests.

**Comment by kalon33** [comment]
@pbnjay thanks for your reply. How much funding do you think this would require?

**Comment by pbnjay** [comment]
@kalon33 - I've sent an email to the address on your github profile. Happy to discuss further offline!
