### ISSUE TITLE
not working after update MacOS High Sierra

### ISSUE THREAD

**Issue by marcelokauffman** [pbnjay/lollipops#28]
It is not working after updating OS. 

I get this after testing

Get http://www.uniprot.org/uniprot/?query=TP53+AND+reviewed:yes+AND+organism:9606+AND+database:pfam&sort=score&columns=id,entry+name,reviewed,genes,organism&format=tab: dial tcp 128.175.240.211:80: i/o timeout

but not lollipop graph anymore

**Comment by pbnjay** [comment]
Can you access that url? Works for me on High Sierra. Sounds like your network is having issues or firewalled.

**Comment by belel** [comment]
Hi I get the a similar error after update:
Get http://pfam.xfam.org/protein/P55317/graphic: dial tcp 193.62.192.83:80: i/o timeout

Did you solve it and how?
Thanks!
