### ISSUE TITLE
pfam returned invalid result 

### ISSUE THREAD

**Issue by ex208** [pbnjay/lollipops#30]
lollipops fail to generate an annotation for several Pfam entries. 
e.g: lollipops -U D2BYD1_DICZ5

**Comment by pbnjay** [comment]
I'm not able to find `D2BYD1_DICZ5` anywhere. Are you sure there is a pfam entry for it? The closest I can find is `D2BYD1`

**Comment by ex208** [comment]
Hi there, 
You are right the accession is D2BYD1. See below the Uniprot entry. However, I still get an invalid result when use -U D2BYD1 (see command prompt below). Thanks a lot. 
<img width="1271" alt="screen shot 2017-12-21 at 16 14 10" src="https://user-images.githubusercontent.com/15181742/34264231-1bf65b62-e66a-11e7-91f7-73fdeb25bed7.png">
<img width="810" alt="screen shot 2017-12-21 at 16 15 05" src="https://user-images.githubusercontent.com/15181742/34264249-2d463d38-e66a-11e7-949c-a8ab43231637.png">
