### ISSUE TITLE
Feature request : Gene name in plot

### ISSUE THREAD

**Issue by aravindsankar91** [pbnjay/lollipops#32]
Hello pbnjay,

I've tried to use this to generate plots for mutations in multiple genes and it has worked great so far. However, do you think it would be possible to allow an option to print the gene name in the plot somewhere ? I'd eventually like to merge the images into a single file and having the gene names on the plot would be handy as opposed to having them in the file name. Just a thought.

Thanks a lot!
Aravind

**Comment by pbnjay** [comment]
In our reports, the gene name is very close to the image already so this would be quite redundant. I imagine it would be fairly trivial to add the names in your merging script as well.
