### ISSUE TITLE
Timeout message

### ISSUE THREAD

**Issue by TMosley** [pbnjay/lollipops#33]
I'm not sure exactly what is going on, but I'm not able to generate a plot. I keep getting this message:

Get http://pfam.xfam.org/protein/Q16829/graphic: dial tcp 193.62.192.83:80: i/o timeout

I've tried using both the Uniprot ID and HGNC gene name. Also I tried downloading the .json script from the pfam website, but I get this message:

json: cannot unmarshal array into Go value of type data.PfamGraphicResponse

And since I've never worked with json I have no idea what it means.

**Comment by pbnjay** [comment]
1st error basically says that you can't connect to pfam (either your internet or pfam's server isn't working right).

2nd message you can simply delete the outermost square brackets from the json file.
