### ISSUE TITLE
i/o timeout to pfam

### ISSUE THREAD

**Issue by dannydesloover2** [pbnjay/lollipops#35]
Haven't been able to get the script working - receiving this error:

Get http://pfam.xfam.org/protein/P38398/graphic: dial tcp 193.62.192.83:80: i/o timeout

**Comment by pbnjay** [comment]
Try again later - pfam's site is not completely reliable.

Also, please use the search - this is a duplicate of #33 and #28 and is not an issue with the code, but depends on network connectivity.
