### ISSUE TITLE
Using a local JSON file

### ISSUE THREAD

**Issue by grrchrr** [pbnjay/lollipops#36]
Hey, 
is there maybe a minimal example for the usage of a local JSON file?  - More specifically: Which of the graphical elements of the PFAM domain generator are recognized/ needed for lollipops to accurately perform the plotting?
I converted my mutational data set to a JSON which works properly with the PFAM domain graphic generator:
![screen shot 2018-06-04 at 11 06 02](https://user-images.githubusercontent.com/39835337/40908530-59d2be86-67e7-11e8-9691-05d56fa5e663.png)
For lollipops I assumed that just the regions information is needed, so I reduced my JSON to that information kind, but I am still getting this error message:
"json: cannot unmarshal string into Go struct field PfamGraphicFeature.display of type bool"

Hope you can help!

Greetings,
grrchrr

**Comment by pbnjay** [comment]
Go's parser is a bit more strict, I believe the issue is that you quoted the bool values eg `"display": "true"` instead of `"display": true`
