### ISSUE TITLE
dial tcp 193.62.193.81:80: i/o timeout

### ISSUE THREAD

**Issue by RiNiculous93** [pbnjay/lollipops#38]
Hey,

I've used lollipops previously but recently when I try to I get the error:

`Get http://www.uniprot.org/uniprot/?query=PMS1+AND+reviewed:yes+AND+organism:9606+AND+database:pfam&sort=score&columns=id,entry+name,reviewed,genes,organism&format=tab: dial tcp 193.62.193.81:80: i/o timeout`

I was wondering if this is a problem on my end or something others are experiencing?

**Comment by pbnjay** [comment]
[Please search issues before reporting a new one](https://github.com/pbnjay/lollipops/issues?utf8=%E2%9C%93&q=i%2Fo+timeout)

**Comment by RiNiculous93** [comment]
Excellent. +1 for passive aggression, very professional.
