### ISSUE TITLE
Optional display exons for primary transcript as well?

### ISSUE THREAD

**Issue by arq5x** [pbnjay/lollipops#4]
Is there any way of extracting information from Ensembl and/or Uniprot that would allow one to visualize the exon boundaries for the associated transcript? This would be very useful for visualizing how variants map from protein domains to coding exons. For example, combining a lollipop plot for TP53 with a plot like this from ExAC:

http://exac.broadinstitute.org/gene/ENSG00000141510

**Comment by pbnjay** [comment]
Right now the plots are entirely coding exons. Plotting the introns as well would be a pretty substantial change to the plots, they're currently in protein space so it would mean breaking up the plot at each splice site and spacing it out, accounting for offsets in the codon positions for each exon, in addition to mapping the exon boundaries along the x-axis. 

If you want to submit a PR I'm happy to provide feedback and include, but this would be a good bit of effort and is not relevant to my current project for this.

**Comment by arq5x** [comment]
Completely understand. Would it be possible to optionally draw lines that project the exon boundaries onto the protein coordinates? That is, ignore the introns, just show how the exons correspond to the proetin sequence and domains.
