### ISSUE TITLE
non-recoverable error occured

### ISSUE THREAD

**Issue by jooysong** [pbnjay/lollipops#41]
Hi,
I was getting this error below.  Any help would be great.

W:\lollipop>lollipops TP53 R273C R175H T125 R248Q
HGNC Symbol:  TP53
Get http://www.uniprot.org/uniprot/?query=TP53+AND+reviewed:yes+AND+organism:9606+AND+database:pfam&sort=score&columns=id,entry+name,reviewed,genes,organism&format=tab: dial tcp: lookup www.uniprot.org: getaddrinfow: A non-recoverable error occurred during a database lookup.

**Comment by jooysong** [comment]
btw, I was using the windows 64 version.

**Comment by pbnjay** [comment]
Looks like the DNS query for uniprot.org failed. Check your internet/network/DNS servers/etc. and try again, but there's not much that can be done in the software if that isn't working.
