### ISSUE TITLE
Options for Color and Size selection

### ISSUE THREAD

**Issue by sararselitsky** [pbnjay/lollipops#5]
I am working with mutation data from multiple cancer types and I would like to plot the mutations of multiple types on one protein and have the color indicate the the different cancer type. Can you alter lollipops so this is possible? Thank you!

**Comment by pbnjay** [comment]
how would you see this working? i think it would be simplest if you just provided the colors up front, versus making the plotter map the cancer type names to colors internally. I can add an input style where you can just add the color to the encoded mutation (something like "V600M#ff0000" to make V600M a red color?)

**Comment by sararselitsky** [comment]
Ok, that sounds good.

**Comment by pbnjay** [comment]
ok i've added this into the latest release: https://github.com/pbnjay/lollipops/releases/tag/v0.95

**Comment by sararselitsky** [comment]
Thank you! This will be very helpful in visualizing my data.

**Comment by sararselitsky** [comment]
Hi Jeremy,

I have another request and I can also leave this request on GitHub if you’d like.

I am working with data sets with many samples in each category and sometimes the pileups are too high for this type of visualization. I attached an example for the gene IDH1. For each location, instead of each sample being represented separately, could one dot for each color be represented, but the size depends on the number of samples?

I know this is a lot of work and would be happy to make you co-author on my cancer mutation paper.

Thank you very much,

Sara 

PS: I noticed you are at UNC-C. I am at UNC-CH.

**Comment by sararselitsky** [comment]
I am working with data sets with many samples in each category and sometimes the pileups are too high for this type of visualization. For each location, instead of each sample being represented separately, could one dot for each color be represented, but the size dependent on the number of samples?

**Comment by pbnjay** [comment]
I've got a version of this, using log-2 scaling (otherwise the single-digits hits are far outweighed by anything over 50.

![screen shot 2015-01-14 at 9 14 16am](https://cloud.githubusercontent.com/assets/161552/5740044/e6ec7be8-9bcd-11e4-8b8e-3c28fc1fac82.png)

**Comment by sararselitsky** [comment]
It looks great! Is it available for download?

**Comment by pbnjay** [comment]
Just cleaned it up and pushed it out: https://github.com/pbnjay/lollipops/releases/tag/v0.96

**Comment by sararselitsky** [comment]
I think there is a bug that switches the colors when they are at the sample location.
