### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by jhchung** [pbnjay/lollipops#6]
Hi,

You've got an interesting tool here. I'm testing it out but have come accross an issue with the annotations. 

For one of the proteins that I am interested in, the annotations from pfam are different from other published sources including uniprot and published articles. Is there a way to add custom domain annotations? For example, to use a tab delimited text file describing the different domains as an input?

Thanks,
-Jonathan

**Comment by pbnjay** [comment]
Does the -U option to provide uniprot ID give the wrong domain info also? I
find it strange that pfam would be significantly different from uniprot.

Jeremy

**Comment by jhchung** [comment]
The protein I am looking at is RIPPLY3. I used `-U P57055` and had no trouble getting the annotations from pfam.

In uniprot, there are two domains (Ripply and WRPW) but in pfam, there is only a Ripply domain with some disordered or low complexity domains but no WRPW domain. Also, the start and stop positions of the ripply domain is very different in the two databases. 

It is strange and I don't think it's a problem with the program itself.
