### ISSUE TITLE
biomart error

### ISSUE THREAD

**Issue by kanikaarora316** [pbnjay/lollipops#7]
Hello,

I downloaded lollipops last month and used it a couple of times, and it worked very well. But unfortunately it's not working anymore. The problem is that it cannot retrieve from Biomart. I get the following error message:
biomart error: 400 Bad Request
I am not sure if I am the only one facing this issue. Can you please let me know how to get around it?
Thanks!

Kanika

**Comment by pbnjay** [comment]
Looks like biomart is down at the moment. So you're not the only one. You can either try again later or provide the uniprot ID directly with `-U`

**Comment by sidnb** [comment]
Hi,
I am getting the same error... I don't it has to do with Biomart being down.  Any other ideas?

[sidnb10@xhost11 lollipops-v0.96-linux64]$ ./lollipops TP53 R273C R175H T125 R248Q
can't find arial.ttf - for more accurate font sizing use -f=/path/to/arial.ttf
HGNC Symbol:  TP53
biomart error: 400 Bad Request

**Comment by pbnjay** [comment]
They made a breaking change to their API. It was fixed in c36d1dc, are you using the latest code or just the binary release?
