### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by sigven** [pbnjay/lollipops#9]
Hi,

I just downloaded the latest version and started testing with some mutations, e.g.

lollipops -o=test.png BRAF V600E

However, I get a bunch of runtime errors I am not able to comprehend (see below) I tried your tool earlier (a previous version I guess) that worked fine. Is this related to go?

---

./lollipops -o=test1.png BRAF V600E

WARNING: unable to find Arial.ttf - for more accurate font sizing add -f=/path/to/arial.ttf
HGNC Symbol:  BRAF
Uniprot/SwissProt Accession:  P15056
Drawing diagram to test1.png
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x60 pc=0x14869e]

goroutine 1 [running]:
code.google.com/p/jamslam-freetype-go/freetype.(*Context).SetDPI(0x0, 0x4052000000000000)
	/Users/jeremy/src/code.google.com/p/jamslam-freetype-go/freetype/freetype.go:297 +0x1e
github.com/pbnjay/lollipops/drawing.(*Settings).DrawPNG(0x59eec0, 0x6b01e8, 0xc8200d2028, 0x4052000000000000, 0xc82000a370, 0x1, 0x1, 0xc8200c4120)
	/Users/jeremy/src/github.com/pbnjay/lollipops/drawing/png.go:38 +0xf1
github.com/pbnjay/lollipops/drawing.DrawPNG(0x6b01e8, 0xc8200d2028, 0x4052000000000000, 0xc82000a370, 0x1, 0x1, 0xc8200c4120)
	/Users/jeremy/src/github.com/pbnjay/lollipops/drawing/png.go:18 +0x76
main.main()
	/Users/jeremy/src/github.com/pbnjay/lollipops/main.go:151 +0x142e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 10 [IO wait]:
net.runtime_pollWait(0x6b18f0, 0x72, 0xc820010180)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200ce140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200ce140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200ce0e0, 0xc8200a9000, 0x1000, 0x1000, 0x0, 0x6ac050, 0xc820010180)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200320a8, 0xc8200a9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x6b1a70, 0xc8200320a8, 0xc8200dc058, 0xc8200a9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82000e8a0, 0xc8200a9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001c720)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001c720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200dc000)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 8 [IO wait]:
net.runtime_pollWait(0x6b19b0, 0x72, 0xc820010180)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820066760, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820066760, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820066700, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x6ac050, 0xc820010180)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200320a0, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x6b1a70, 0xc8200320a0, 0xc820018108, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82000e7a0, 0xc82001b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82001c600)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82001c600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200180b0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc8200180b0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc8200dc000)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

**Comment by pbnjay** [comment]
It's a silly bug. I forgot to check that the arial font was found before using it. For a workaround, you can either use -f as mentioned in the first line of output, or copy arial.ttf to your working directory. I'll try to get a fix out in the next few days.

**Comment by sigven** [comment]
Thanks for the rapid response. Works fine now. And thanks for an excellent tool:)
